# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('photo_url', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('twitter_screen_name', models.CharField(max_length=100)),
                ('twitter_since_id', models.CharField(blank=True, max_length=30, null=True)),
                ('twitter_last_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2083)),
                ('url_title', models.CharField(blank=True, max_length=500, null=True)),
                ('url_image', models.CharField(blank=True, max_length=300, null=True)),
                ('url_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('twitter_id', models.CharField(max_length=30)),
                ('twitter_text', models.CharField(max_length=1200)),
                ('twitter_favorite_count', models.IntegerField(blank=True, null=True)),
                ('twitter_retweet_count', models.IntegerField(blank=True, null=True)),
                ('twitter_date_posted', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservice.Channel')),
            ],
            options={
                'ordering': ('-twitter_date_posted',),
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('country', models.ManyToManyField(blank=True, to='webservice.Country')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='country',
            field=models.ManyToManyField(blank=True, to='webservice.Country'),
        ),
        migrations.AddField(
            model_name='channel',
            name='latest_news',
            field=models.ManyToManyField(blank=True, related_name='latest_news', to='webservice.News'),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriber',
            field=models.ManyToManyField(blank=True, to='webservice.Subscriber'),
        ),
    ]
