# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservice.Category'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='channel',
            field=models.ManyToManyField(blank=True, to='webservice.Channel'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
