# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0005_auto_20160319_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='newshistory',
            name='number_of_visit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
