# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0008_auto_20160319_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-created_date',), 'verbose_name_plural': 'Bookmark'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-modified_date',), 'verbose_name_plural': 'Histories'},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='photo_url',
            new_name='profile_image_url',
        ),
        migrations.AlterField(
            model_name='history',
            name='number_of_visit',
            field=models.IntegerField(default=1),
        ),
    ]
