# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0009_auto_20160325_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_channel',
            field=models.IntegerField(default=0),
        ),
    ]
