# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0011_auto_20160327_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webservice.Category'),
            preserve_default=False,
        ),
    ]
