# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0012_auto_20160327_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='webservice.Category'),
        ),
    ]
