# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0013_auto_20160327_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.Channel')),
            ],
            options={
                'ordering': ('channel__name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDFA', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='country',
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-created_date',), 'verbose_name_plural': 'Histories'},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='history',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='history',
            name='number_of_visit',
        ),
        migrations.RemoveField(
            model_name='history',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.User'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webservice.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webservice.User'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('user', 'channel')]),
        ),
    ]
